xmlpatternssdk: Fix compilation with MSVC 2015.
Change exported class ExpressionInfo to not inherit QPair<>, use normal
member variables for the name/details strings instead.

Exporting classes inheriting QPair<> is not possible due to a
compiler bug in MSVC 2015.

src/corelib/tools/qpair.h(83): error C2065: 'TT1': undeclared identifier
src/corelib/tools/qpair.h(83): note: This diagnostic occurred in the compiler generated function 'QPair<QString,QString> &QPair<QString,QString>::operator =(QPair<TT1,TT2> &&) noexcept(<expr>)'
src/corelib/tools/qpair.h(83): error C2923: 'std::is_nothrow_assignable': 'TT1' is not a valid template type argument for parameter '_From'

Task-number: QTBUG-49658
Change-Id: Ib2c27a4c2b0aae28b4de6086c8ddc0220e205075
Reviewed-by: Kai Koehne <kai.koehne@theqtcompany.com>
Reviewed-by: Jędrzej Nowacki <jedrzej.nowacki@theqtcompany.com>