Fix annoying warning in qtxmlpatterns about a value too big for the enum
api/qcoloroutput_p.h:74:60: error: signed shift result (0xFFFFF00000) requires 41 bits to represent, but 'int' only has 32 bits [-Werror,-Wshift-overflow]

The masks don't look right anyway. Let's just hardcode them according
to how many colours are used.

Change-Id: Idd3438ecab3fb666bd84929fb731011224b9c68e
Reviewed-by: Lars Knoll <lars.knoll@digia.com>