Fix compilation with the recent qtbase
After ce27e6f0222d2feb6f15ecf6e2670ebc3ceb5a15 QXmlUtils::isChar() takes
char32_t instead of QChar. This fixes:

 error: no viable conversion from 'const QChar' to 'char32_t'

Fixes: QTBUG-104707
Change-Id: I8197b6e3303b3e14b9da81d4cc0497aea173af0a
Reviewed-by: Marc Mutz <marc.mutz@qt.io>