Remove the use of the "register" keyword
It's deprecated in C++14. Found by Clang:

error: 'register' storage class specifier is deprecated [-Werror,-Wdeprecated-register]

Change-Id: Ib306f8f647014b399b87ffff13f23d75e8255950
Reviewed-by: Olivier Goffart (Woboq GmbH) <ogoffart@woboq.com>