Fix warnings found by clang: private members unused in classes
These are private classes, so there's no need to keep binary
compatibility or reserved members.

qabstractxmlpullprovider_p.h:103:41: error: private field 'd' is not used [-Werror,-Wunused-private-field]
projectedexpression_p.h:124:55: error: private field 'm_axis' is not used [-Werror,-Wunused-private-field]
qprojectedexpression_p.h:154:41: error: private field 'm_right' is not used [-Werror,-Wunused-private-field]

Change-Id: Idd46da87aaa85124b285cdcf01cf76eaa16e86c3
Reviewed-by: Robin Burchell <robin+qt@viroteck.net>