Add missing qqmlfile.h include
Fixes the following error on Ubuntu 18.04.2 with g++ 7.4.0:

/home/mitch/dev/qt5-dev/qtxmlpatterns/src/imports/xmllistmodel/qqmlxmllistmodel.cpp: In member function ‘void QQuickXmlListModel::reload()’:
/home/mitch/dev/qt5-dev/qtxmlpatterns/src/imports/xmllistmodel/qqmlxmllistmodel.cpp:1063:16: error: ‘QQmlFile’ has not been declared
     } else if (QQmlFile::isLocalFile(d->src)) {
                ^~~~~~~~
/home/mitch/dev/qt5-dev/qtxmlpatterns/src/imports/xmllistmodel/qqmlxmllistmodel.cpp:1064:20: error: ‘QQmlFile’ has not been declared
         QFile file(QQmlFile::urlToLocalFileOrQrc(d->src));
                    ^~~~~~~~

Change-Id: I2ff7f898d42f51f8d0c5a1116049278a502ba343
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>